apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ps0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ps0
        role: ps
    spec:
      containers:
      - name: ps0
        image: tensorflow/tensorflow:1.0.1
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["curl -L https://raw.githubusercontent.com/ogre0403/Distributed-GPU-TensorFlow-on-K8S/master/lab03/bg_dist.py  -o /opt/bg_dist.py; 
                python /opt/bg_dist.py --job_name=ps --task_index=0"]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tf-ps0-service
  name: ps0
spec:
  selector:
    app: ps0
  ports:
  - port: 2222
    targetPort: 2222
