apiVersion: batch/v1
kind: Job
metadata:
  name: worker1
spec:
  template:
    metadata:
      labels:
        app: worker1
        role: worker
    spec:
      containers:
      - name: worker1
        image: tensorflow/tensorflow:1.0.1
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["curl -L https://raw.githubusercontent.com/ogre0403/Distributed-GPU-TensorFlow-on-K8S/master/lab03/bg_dist.py  -o /opt/bg_dist.py;
                python /opt/bg_dist.py --job_name=worker --task_index=1"]
      restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tf-worker1-service
  name: worker1
spec:
  selector:
    app: worker1
  ports:
  - port: 2222
    targetPort: 2222
