---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab06-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/k8s/lab06

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lab06-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
